name: "Publish to an AWS SQS Queue"
description: "Publish a JSON message to an AWS SQS queue"

inputs:
  AWS_ACCESS_KEY_ID:
    description: "The access key ID for the AWS IAM user (16-128 characters)"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "The secret access key for the AWS IAM user (40 characters)"
    required: true
  AWS_REGION:
    description: "The AWS region where the SQS queue exists"
    required: true
    default: "us-east-1"
  MESSAGE:
    description: "The message you would like to publish to SQS"
    required: true
  AWS_SNS_TOPIC_ARN:
    description: "The URL of the SQS queue to publish to"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'check-circle'
  color: 'orange'
