name: pre-commit

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  push:
    branches: [main]

jobs:
  pre-commit-ci:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: check out code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3

      - name: setup python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4
        with:
          python-version: "3.11"

      - name: install pipenv
        run: |
          python -m pip install pipenv

      - id: cache-pipenv
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920  # v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: install dependencies
        run: |
          pipenv install --dev

      - name: install pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
