name: take-issue

on:
  issue_comment:

jobs:
  assign:
    name: Take the issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: take the issue
      uses: bdougie/take-action@28b86cd8d25593f037406ecbf96082db2836e928
      with:
        message: Thanks for taking this issue! Let us know if you have any questions!
        trigger: .take
        token: ${{ secrets.GITHUB_TOKEN }}
